version: '3.8'

services:
  builder:
    image: actions-lede-builder:latest
    container_name: openwrt-base-builder
    volumes:
      - ..:/workdir/Actions-LEDE
    stdin_open: true
    tty: true
    command: /bin/bash

  build:
    image: actions-lede-builder:latest
    container_name: openwrt-base-build
    volumes:
      - ..:/workdir/Actions-LEDE
    command: >
      bash -c "cd /workdir/Actions-LEDE && bash build.sh"
