#
# This is free software, lisence use MIT.
#
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
#
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Merge-upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'
  watch:
    types:
      - 'started'

jobs:
  merge:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
        lfs: true
        token: ${{ secrets.SEC_TOKEN }}

    - name: Set git identity
      run : |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Load upstream commits
      run:  |
        git remote add upstream https://github.com/P3TERX/Actions-OpenWrt
        git fetch upstream
        git rebase upstream/main

    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: main
      run: git push --force-with-lease origin $DOWNSTREAM_BRANCH
